var CANVAS_WIDTH = 1024;
var CANVAS_HEIGHT = 768;
var DISABLE_SOUND_MOBILE = true;

var FPS_TIME      = 1000/24;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP   = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT  = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END   = 5;
var ON_PRESS_MOVE = 6;

var NUM_LANGUAGES = 6;
var TIME_LEVEL;
var MAX_CHAR_VALUE;
var CELL_WIDTH = 80;
var CELL_HEIGHT = 80;
var MAX_WORD_LENGTH = 8;
var MAX_WORDS_WRITTEN_VIEWABLE = 22;
var SCORE_WORD_WRONG;
var NUM_ROWS = 7;
var NUM_COLS = 7;

var LABEL_LANG_0 = "LANG_ENG";
var LABEL_LANG_1 = "LANG_GER";
var LABEL_LANG_2 = "LANG_SPA";
var LABEL_LANG_3 = "LANG_FRA";
var LABEL_LANG_4 = "LANG_ITA";
var LABEL_LANG_5 = "LANG_POR";